version: "2"
services:
  godaddy-dns:
    build: .
    container_name: godaddy-dns
    network_mode: host
    environment:
      - GODADDY_DDNS_KEY=${GODADDY_DDNS_KEY:?}
      - GODADDY_DDNS_SECRET=${GODADDY_DDNS_SECRET:?}
      - GODADDY_DDNS_NAME=${GODADDY_DDNS_NAME:?}
      - GODADDY_DDNS_DOMAIN=${GODADDY_DDNS_DOMAIN:?}
      - GODADDY_DDNS_FULL_LOG=${GODADDY_DDNS_FULL_LOG:?}
      - GODADDY_DDNS_IPV6=${GODADDY_DDNS_IPV6:-1}
